### ISSUE TITLE
Clarification on workflow

### ISSUE THREAD

**Issue by apcordeiro** [AshrithSagar/EEG-Imagined-speech-recognition#3]
Hello, thank you so much for the impressive work.

I was wondering if it would be possible for you to clarify the steps required to complete the pipeline you have built. For example, after extracting the features for the KaraOne dataset, what should one do next? How are the features and the TRF dataset related (if they are)? 

Furthermore, I didn't understand where do the models come from when using, for example, `ifs-karaone.py`? Do we have to download models ourselves?

Thank you so much.

**Comment by AshrithSagar** [comment]
Hi, Thanks for the comment!

The documentation parts are still a work in progress.
I will update the documentation with the entire procedure for using the pipeline.

The features and the TRF dataset are two separate pipelines.
You can use either of them as your features for the classification tasks.

You can define your models and plug and play in the pipeline.
The exact procedure will take some time to show up in the documentation, but briefly stated, you need to define a function in `model.py`, which should be present in your model_dir. Each model can 
In it, there should be a function called `model()` which returns your model, and
